"""create repository symbols

Revision ID: 20260703_0001_create_repository_symbols
Revises: 20260702_1715_create_repository_files
Create Date: 2026-07-03 00:01:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '20260703_0001_create_repository_symbols'
down_revision = '20260702_1715'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_symbols',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('repository_file_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('symbol_name', sa.String(length=512), nullable=False),
    sa.Column('symbol_type', sa.String(length=64), nullable=False),
    sa.Column('parent_symbol', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('start_column', sa.Integer(), nullable=True),
    sa.Column('end_column', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_symbol'], ['repository_symbols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_file_id'], ['repository_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_repository_symbols_created_at', 'repository_symbols', ['created_at'], unique=False)
    op.create_index('ix_repository_symbols_language_symbol_type', 'repository_symbols', ['language', 'symbol_type'], unique=False)
    op.create_index('ix_repository_symbols_location', 'repository_symbols', ['repository_file_id', 'start_line', 'end_line'], unique=False)
    op.create_index('ix_repository_symbols_repository_file_id_symbol_type', 'repository_symbols', ['repository_file_id', 'symbol_type'], unique=False)
    op.create_index(op.f('ix_repository_symbols_language'), 'repository_symbols', ['language'], unique=False)
    op.create_index(op.f('ix_repository_symbols_parent_symbol'), 'repository_symbols', ['parent_symbol'], unique=False)
    op.create_index(op.f('ix_repository_symbols_repository_file_id'), 'repository_symbols', ['repository_file_id'], unique=False)
    op.create_index(op.f('ix_repository_symbols_symbol_name'), 'repository_symbols', ['symbol_name'], unique=False)
    op.create_index(op.f('ix_repository_symbols_symbol_type'), 'repository_symbols', ['symbol_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_symbols_symbol_type'), table_name='repository_symbols')
    op.drop_index(op.f('ix_repository_symbols_symbol_name'), table_name='repository_symbols')
    op.drop_index(op.f('ix_repository_symbols_repository_file_id'), table_name='repository_symbols')
    op.drop_index(op.f('ix_repository_symbols_parent_symbol'), table_name='repository_symbols')
    op.drop_index(op.f('ix_repository_symbols_language'), table_name='repository_symbols')
    op.drop_index('ix_repository_symbols_repository_file_id_symbol_type', table_name='repository_symbols')
    op.drop_index('ix_repository_symbols_location', table_name='repository_symbols')
    op.drop_index('ix_repository_symbols_language_symbol_type', table_name='repository_symbols')
    op.drop_index('ix_repository_symbols_created_at', table_name='repository_symbols')
    op.drop_table('repository_symbols')
    # ### end Alembic commands ###
